# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e8948dce4c0809c90be11182400680dcca60bef3b40741a9204b747361721987090ca9f381d306f77387f542f4d56f15c289323cc5a3d14db68253127fd6e0

test:
  secret_key_base: a3bc5ccaafbc8cfae05eff4ffd05fdb27d5099b8c1759f6eec350771c15e62659db4836dbe4cc081aa026165211e529bb9507d37053789f1b220d8f03b9cfbdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
